<?php

namespace SlimBundle\Repository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sous_CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function createaQueryBuilder()
    {
        return $this->getEntityManager()->createQueryBuilder()->select('u')->from('SlimBundle:Sous_Categorie','u')
            ->where('u.idCategorie = :p')->setParameter('p',4);
    }
    public function createaQueryBuilder2()
    {
        return $this->getEntityManager()->createQueryBuilder()->select('u')->from('SlimBundle:Sous_Categorie','u')
            ->where('u.idCategorie = :p')->setParameter('p',3);
    }
    public function createaQueryBuilder3()
    {
        return $this->getEntityManager()->createQueryBuilder()->select('u')->from('SlimBundle:Sous_Categorie','u')
            ->where('u.idCategorie = :p')->setParameter('p',1);
    }
    public function createaQueryBuilder4()
    {
        return $this->getEntityManager()->createQueryBuilder()->select('u')->from('SlimBundle:Sous_Categorie','u')
            ->where('u.idCategorie = :p')->setParameter('p',2);
    }
}
