deals:
    resource: "@DealsBundle/Resources/config/routing.yml"
    prefix:   /deals

oussama:
    resource: "@OussamaBundle/Resources/config/routing.yml"
    prefix:   /oussama

ons:
    resource: "@OnsBundle/Resources/config/routing.yml"
    prefix:   /ons

slim:
    resource: "@SlimBundle/Resources/config/routing.yml"
    prefix:   /slim

skander:
    resource: "@SkanderBundle/Resources/config/routing.yml"
    prefix:   /skander

amir:
    resource: "@AmirBundle/Resources/config/routing.yml"
    prefix:   /amir

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /a
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
App_bon_plan_layout:
    path:     /layout
    defaults: { _controller: AppBundle:BonPlan:layout }
App_bon_plan_home:
    path:     /home
    defaults: { _controller: AppBundle:BonPlan:home }
App_bon_plan_contact:
    path:     /contact
    defaults: { _controller: AppBundle:BonPlan:contact }
App_bon_plan_admin:
    path:     /admin/
    defaults: { _controller: AppBundle:BonPlan:admin }
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message
App_bon_plan_ajout_restaurant_admin:
    path:     /admin/ajout_restaurant
    defaults: { _controller: AmirBundle:Admin:ajout_restaurant }
App_bon_plan_ajout_hotel_admin:
    path:     /admin/ajout_hotel
    defaults: { _controller: AmirBundle:Admin:ajout_hotel }
App_bon_plan_ajout_culture_admin:
    path:     /admin/ajout_culture
    defaults: { _controller: AmirBundle:Admin:ajout_culture }
App_bon_plan_ajout_beaute_admin:
    path:     /admin/ajout_beaute
    defaults: { _controller: AmirBundle:Admin:ajout_beaute }
App_bon_plan_list_restaurant_admin:
    path:     /admin/list_restaurant
    defaults: { _controller: AmirBundle:Admin:list_restaurant }
App_bon_plan_delete_restaurant_admin:
    path:     /admin/delete/{id}
    defaults: { _controller: AmirBundle:Admin:delete }
App_bon_plan_update_restaurant_admin:
    path:     /admin/update/{id}
    defaults: { _controller: AmirBundle:Admin:update }
App_bon_plan_list_hotel_admin:
    path:     /admin/list_hotel
    defaults: { _controller: AmirBundle:Admin:list_hotels}
App_bon_plan_list_beaute_admin:
    path:     /admin/list_beaute
    defaults: { _controller: AmirBundle:Admin:list_beaute }
App_bon_plan_list_culture_admin:
    path:     /admin/list_culture
    defaults: { _controller: AmirBundle:Admin:list_culture }
App_bon_plan_update_beaute_admin:
    path:     /admin/updatebeaute/{id}
    defaults: { _controller: AmirBundle:Admin:updatebeaute }
App_bon_plan_update_culture_admin:
    path:     /admin/updateculture/{id}
    defaults: { _controller: AmirBundle:Admin:updateculture }
App_bon_plan_update_hotel_admin:
    path:     /admin/updatehotel/{id}
    defaults: { _controller: AmirBundle:Admin:updatehotel }


